friend_1=input("enter your name")
friend_1_bday=input ("enter your bday")
friend_2 = input("enter your name")
friend_2_bday = input ("enter your bday")
friend_3 = input("enter your name")
friend_3_bday = input ("enter your bday")
friend_4 = input("enter your name")
friend_4_bday = input ("enter your bday")
friend_5 = input("enter your name")
friend_5_bday = input ("enter your bday")
print(friend_1 +friend_1_bday)
print(friend_2 +friend_2_bday)
print(friend_3+ friend_3_bday)
print(friend_4 +friend_4_bday)
print(friend_5 + friend_5_bday)